<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackageId>Expected</PackageId>
    <Version>0.1.11</Version>
    <Authors>jipg</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/jipgg/Expected</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
      <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

<!-- <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles> -->
<!-- <CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath> -->
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Expected.Analyzers\Expected.Analyzers.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />

    <ProjectReference Include="..\Expected.Generators\Expected.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
  </ItemGroup>
<ItemGroup>
  <Content Include="..\Expected.Analyzers\bin\$(Configuration)\netstandard2.0\Expected.Analyzers.dll"
           Pack="true"
           PackagePath="analyzers/dotnet/cs/" />

  <Content Include="..\Expected.Generators\bin\$(Configuration)\netstandard2.0\Expected.Generators.dll"
           Pack="true"
           PackagePath="analyzers/dotnet/cs/" />
</ItemGroup>

</Project>
