<Project Sdk="Microsoft.NET.Sdk">
   <PropertyGroup>
      <TargetFramework>netstandard2.0</TargetFramework>
      <NoWarn>IDE0040 IDE0061 IDE0008 IDE0011 IDE0046</NoWarn>
      <ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>13.0</LangVersion>
		<OutputItemType>Analyzer</OutputItemType>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
		<EnableAnalyzerReleaseTracking>true</EnableAnalyzerReleaseTracking>
		<AnalyzerId>EX</AnalyzerId>
		<AnalyzerVersion>0.1.0</AnalyzerVersion>
   </PropertyGroup>
   <ItemGroup>
      <!-- <None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs/$(AssemblyName).dll" /> -->
		<AdditionalFiles Include="AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="AnalyzerReleases.Unshipped.md" />
   </ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
	</ItemGroup>
</Project>
